- name: Install Kubernetes apt deps
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg
    state: present
    update_cache: true

- name: Add Kubernetes apt key
  shell: |
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.34/deb/Release.key \
    | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Add Kubernetes repo
  copy:
    dest: /etc/apt/sources.list.d/kubernetes.list
    content: |
      deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.34/deb/ /

- name: Install kube components
  apt:
    name:
      - kubelet=1.34.1-1.1
      - kubeadm=1.34.1-1.1
      - kubectl=1.34.1-1.1
    state: present
    update_cache: true

- name: Hold kube packages
  command: apt-mark hold kubelet kubeadm kubectl

- name: Configure crictl
  command: crictl config runtime-endpoint unix:///var/run/containerd/containerd.sock
  changed_when: false
